"""
Distribution Analysis — Johnson SU & Azzalini Skewed-t
======================================================
Unified distribution-analysis toolkit. Provides the full fitting and diagnostic
pipeline for the two candidate return distributions used in this project:

  * Johnson SU (Johnson, 1949)          — see PART 1
  * Azzalini & Capitanio (2003) Skewed-t — see PART 2

Each family exposes the same workflow: core pdf/cdf/sampling, Maximum Likelihood
estimation, a Minimum Distance Estimation (MDE) fit to forecasted quantiles, an
end-to-end fit-and-diagnose helper, conditional-vs-unconditional comparison
plots, and an out-of-sample parameter / PIT-calibration backtest.

Naming convention
-----------------
Johnson SU helpers carry the ``jsu`` marker (``jsu_pdf``, ``fit_jsu``,
``mde_jsu``/``mde_jsu_weighted``, ``compare_distributions_jsu`` …) and the
generic OOS helpers (``generate_oos_parameters``, ``evaluate_oos_pit``) belong to
the JSU family. Skewed-t helpers carry the ``skewt`` marker (``skewt_pdf``,
``fit_skewt``, ``mde_distfit_skewt``, ``compare_distributions_skewt``,
``generate_oos_parameters_skewt``, ``evaluate_oos_pit_skewt`` …).

The downstream risk/vulnerability metrics live in ``auxi.vulnerability_metrics``
and consume ``fit_jsu`` / ``mde_jsu_weighted`` from here.

References
----------
Johnson, N. L. (1949). Systems of frequency curves generated by methods of
translation. Biometrika, 36(1/2), 149-176.
Azzalini, A., & Capitanio, A. (2003). Distributions generated by perturbation of
symmetry with emphasis on a multivariate skew t-distribution. JRSS-B, 65(2).
"""

import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats, optimize
from scipy.optimize import minimize
from scipy.stats import johnsonsu, kstest, norm
from tqdm import tqdm

from statsmodels.sandbox.distributions.extras import ACSkewT_gen

from auxi.qreg import q_reg

# Azzalini Skewed-t generator instance; behaves like a scipy.stats distribution.
scipy_skewt = ACSkewT_gen()
scipy_skewt.name = "Azzalini_SkewT"


# ###########################################################################
# PART 1 — JOHNSON SU DISTRIBUTION
# ###########################################################################


def jsu_pdf(x, gamma, delta, loc, scale):
    """
    Probability Density Function of the Johnson SU distribution.

    Parameters
    ----------
    x     : array-like  – evaluation points
    gamma : float       – skewness parameter
    delta : float       – shape parameter (> 0)
    loc   : float       – location parameter
    scale : float       – scale parameter (> 0)

    Returns
    -------
    pdf values (array)
    """
    x = np.asarray(x, dtype=float)
    z = (x - loc) / scale                          # standardise
    arcsinh_z = np.arcsinh(z)                      # arcsinh(z) = log(z + sqrt(z^2+1))
    kernel = gamma + delta * arcsinh_z
    return (delta / (scale * np.sqrt(2 * np.pi) * np.sqrt(1 + z**2))
            * np.exp(-0.5 * kernel**2))


def jsu_cdf(x, gamma, delta, loc, scale):
    """
    Cumulative Distribution Function of the Johnson SU distribution.

    F(x) = Φ(γ + δ · arcsinh((x − loc) / scale))

    Parameters
    ----------
    x     : array-like
    gamma : float
    delta : float  (> 0)
    loc   : float
    scale : float  (> 0)

    Returns
    -------
    cdf values in [0, 1] (array)
    """
    x = np.asarray(x, dtype=float)
    z = (x - loc) / scale
    return stats.norm.cdf(gamma + delta * np.arcsinh(z))


# ──────────────────────────────────────────────
# 2.  Random number generation
# ──────────────────────────────────────────────

def jsu_sample(gamma, delta, loc, scale, size):
    """
    Draw i.i.d. samples from a Johnson SU distribution.

    Uses the closed-form inverse-CDF:
        X = loc + scale * sinh((Z − gamma) / delta),  Z ~ N(0,1)

    Parameters
    ----------
    gamma, delta, loc, scale : float – distribution parameters
    size : int – number of observations to generate

    Returns
    -------
    sorted numpy array of length `size`
    """
    z = np.random.standard_normal(size)
    samples = loc + scale * np.sinh((z - gamma) / delta)
    return np.sort(samples)


# ──────────────────────────────────────────────
# 3.  Maximum-likelihood estimation
# ──────────────────────────────────────────────
def fit_jsu(data, x0=None):
    """
    Fit the Johnson SU distribution to `data` via Maximum Likelihood Estimation
    using Nelder-Mead optimisation. (Versión Robusta)

    Parameters
    ----------
    data : array-like  – observed data (NaNs removed automatically)
    x0   : list or None – optional starting point [gamma, delta, loc, scale].
           When None, defaults to [0, 1, mean(data), std(data)].
           Pass the previous window's result for warm starts in rolling loops.
    """
    # 1. Convertir a array y ELIMINAR NaNs de forma automática
    data = np.asarray(data, dtype=float)
    data = data[~np.isnan(data)]

    n = len(data)

    # 2. Filtro de seguridad: No se puede ajustar una campana a menos de 2 puntos
    if n < 2:
        raise ValueError(f"fit_jsu requiere al menos 2 observaciones históricas. "
                         f"Solo has pasado {n}. ¿Pasaste 'realized' en lugar del histórico?")

    mean_guess = np.mean(data)
    std_guess  = np.std(data)

    # 3. Filtro de seguridad: Si todos los datos son iguales, la volatilidad es 0
    if std_guess == 0:
        std_guess = 1e-3  # Evita división por cero

    def neg_log_likelihood(params):
        gamma_p, delta_p, loc_p, scale_p = params

        # Forzar positividad de los parámetros condicionados
        delta_p = abs(delta_p)
        scale_p = abs(scale_p)

        # Evitar que el optimizador pruebe escalas minúsculas que causan Overflow
        if scale_p < 1e-6: scale_p = 1e-6
        if delta_p < 1e-6: delta_p = 1e-6

        # Suppress overflow/invalid warnings: extreme params produce 0 PDF,
        # which is handled by the floor below. Returning a large finite penalty
        # keeps the gradient signal alive and prevents NaN propagation.
        with np.errstate(over='ignore', invalid='ignore', divide='ignore'):
            pdf_vals = jsu_pdf(data, gamma_p, delta_p, loc_p, scale_p)
            ll = -np.sum(np.log(np.maximum(pdf_vals, 1e-300)))

        return ll if np.isfinite(ll) else 1e10

    warm = x0 is not None
    if x0 is None:
        x0 = [0.0, 1.0, mean_guess, std_guess]

    maxiter = 2_000 if warm else 10_000
    maxfev  = 4_000 if warm else 20_000

    res = optimize.minimize(neg_log_likelihood, x0, method='Nelder-Mead',
                            options={'xatol': 1e-8, 'fatol': 1e-8,
                                     'maxiter': maxiter, 'maxfev': maxfev})

    if not res.success:
        print(f"Warning (fit_jsu): El optimizador pudo no haber convergido. Mensaje: {res.message}")

    gamma_hat, delta_hat, loc_hat, scale_hat = res.x
    return gamma_hat, abs(delta_hat), loc_hat, abs(scale_hat)

# ──────────────────────────────────────────────
# 4.  Distribution summary
# ──────────────────────────────────────────────

def jsu_summary(gamma, delta, loc, scale):
    """
    Print a formatted summary of the fitted JSU parameters and their
    interpretations.

    Parameters
    ----------
    gamma, delta, loc, scale : float – fitted parameters
    """
    print("=" * 50)
    print("JOHNSON SU — FITTED PARAMETERS")
    print("=" * 50)
    print(f"  gamma  (skewness)      : {gamma:+.6f}")
    print(f"  delta  (shape)         : {delta:.6f}")
    print(f"  loc    (location)      : {loc:+.6f}")
    print(f"  scale  (scale)         : {scale:.6f}")
    print("-" * 50)
    # Closed-form moments of JSU (Johnson 1949)
    omega = np.exp(1.0 / delta**2)
    jsu_mean = loc - scale * np.sqrt(omega) * np.sinh(gamma / delta)
    jsu_var  = (scale**2 / 2) * (omega - 1) * (omega * np.cosh(2 * gamma / delta) + 1)
    print(f"  Implied mean           : {jsu_mean:+.6f}")
    print(f"  Implied std dev        : {np.sqrt(jsu_var):.6f}")
    skew_dir = "right (positive)" if gamma < 0 else "left (negative)"
    print(f"  Skew direction         : {skew_dir}  (gamma={gamma:+.4f})")
    heaviness = "heavy" if delta < 1 else "moderate/light"
    print(f"  Tail thickness         : {heaviness}  (delta={delta:.4f})")
    print("=" * 50)


# ──────────────────────────────────────────────
# 5.  Diagnostic plots
# ──────────────────────────────────────────────

def jsu_plot(returns, gamma, delta, loc, scale, ticker="Asset"):
    """
    Produce a 2×2 diagnostic figure for the JSU fit:

      [0,0] Histogram + fitted PDF
      [0,1] Empirical CDF vs theoretical CDF
      [1,0] PP-plot  (theoretical quantiles on x, empirical on y)
      [1,1] QQ-plot  (theoretical quantiles on x, sample quantiles on y)

    Parameters
    ----------
    returns          : sorted 1-D numpy array of observed returns
    gamma, delta,
    loc, scale       : float – fitted JSU parameters
    ticker           : str   – label used in plot titles
    """
    returns = np.sort(np.asarray(returns, dtype=float))
    n   = len(returns)
    edf = np.arange(1, n + 1) / n

    # Fine grid for smooth curves
    x_grid = np.linspace(returns.min(), returns.max(), 500)

    fig, axes = plt.subplots(2, 2, figsize=(13, 9))
    fig.suptitle(f"{ticker} — Johnson SU Fit", fontsize=14, fontweight="bold")

    # ── [0,0]  PDF ───────────────────────────────────────────────────────────
    ax = axes[0, 0]
    ax.hist(returns, bins=60, density=True, alpha=0.45,
            color="steelblue", label="Empirical (histogram)")
    ax.plot(x_grid, jsu_pdf(x_grid, gamma, delta, loc, scale),
            color="crimson", linewidth=2, label="JSU PDF")
    ax.set_title("Density: Histogram vs JSU PDF")
    ax.set_xlabel("Returns")
    ax.set_ylabel("Density")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ── [0,1]  Inverse CDF (Quantile Function) ───────────────────────────────
    ax = axes[0, 1]
    # Empirical quantile function: probability on x, return value on y
    ax.step(edf, returns, color="black", linewidth=1.5,
            label="Empirical Quantile", where="post")
    # Theoretical quantile function: Q(p) = loc + scale * sinh((Φ⁻¹(p) − γ) / δ)
    p_grid = np.linspace(0.001, 0.999, 500)
    q_grid = loc + scale * np.sinh((stats.norm.ppf(p_grid) - gamma) / delta)
    ax.plot(p_grid, q_grid, color="crimson", linewidth=2,
            label="JSU Quantile Function", alpha=0.8)
    ax.set_title("Empirical vs Theoretical Quantile Function (Inverse CDF)")
    ax.set_xlabel("Cumulative Probability")
    ax.set_ylabel("Returns")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ── [1,0]  PP-plot ───────────────────────────────────────────────────────
    ax = axes[1, 0]
    theoretical_cdf = jsu_cdf(returns, gamma, delta, loc, scale)
    ax.scatter(theoretical_cdf, edf, s=6, color="steelblue", alpha=0.6)
    ax.plot([0, 1], [0, 1], color="crimson", linewidth=1.5,
            linestyle="--", label="Perfect fit")
    ax.set_title("PP-Plot")
    ax.set_xlabel("Theoretical CDF")
    ax.set_ylabel("Empirical CDF")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # ── [1,1]  QQ-plot ───────────────────────────────────────────────────────
    ax = axes[1, 1]
    # Theoretical quantiles at the empirical probability points
    # JSU quantile: loc + scale * sinh((Phi^{-1}(p) - gamma) / delta)
    theoretical_quantiles = (loc
                             + scale * np.sinh(
                                 (stats.norm.ppf(edf) - gamma) / delta))
    ax.scatter(theoretical_quantiles, returns, s=6, color="steelblue", alpha=0.6)
    q_min = min(theoretical_quantiles.min(), returns.min())
    q_max = max(theoretical_quantiles.max(), returns.max())
    ax.plot([q_min, q_max], [q_min, q_max], color="crimson",
            linewidth=1.5, linestyle="--", label="Perfect fit")
    ax.set_title("QQ-Plot")
    ax.set_xlabel("Theoretical Quantiles (JSU)")
    ax.set_ylabel("Sample Quantiles")
    ax.legend()
    ax.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()


# ──────────────────────────────────────────────
# 6.  Monte-Carlo corrected KS test
# ──────────────────────────────────────────────

def _mde_jsu_init(fcq, tau_levels):
    """
    Data-driven start for the JSU minimum-distance fit:
    [gamma=0, delta=1, loc=median forecast quantile, scale=normal-equivalent spread].
    Using the spread of the forecast quantiles (instead of a fixed literature
    scale) keeps the optimiser well-conditioned regardless of the units of the
    returns and stops it stalling at the initial guess.
    """
    fcq = np.asarray(fcq, dtype=float)
    taus = np.asarray(tau_levels, dtype=float)
    order = np.argsort(taus)
    taus, fcq = taus[order], fcq[order]
    loc0 = float(np.interp(0.5, taus, fcq))
    lo = max(float(taus.min()), 0.05)
    hi = min(float(taus.max()), 0.95)
    qlo, qhi = float(np.interp(lo, taus, fcq)), float(np.interp(hi, taus, fcq))
    z = norm.ppf(hi) - norm.ppf(lo)
    scale0 = max((qhi - qlo) / z if z > 0 else 1.0, 1e-3)
    return [0.0, 1.0, loc0, scale0]


def _mde_jsu_solve(loss_function, x0, bounds):
    """
    L-BFGS-B first, then a derivative-free Nelder-Mead fallback if the
    gradient solver stalls at the starting point or fails. The loss returns
    +inf for invalid parameters (scale<=0 or delta<=0), so Nelder-Mead stays
    feasible without explicit bounds.
    """
    res = minimize(loss_function, x0, method='L-BFGS-B', bounds=bounds,
                   options={'maxiter': 1000, 'ftol': 1e-12})
    stalled = (not res.success) or np.allclose(res.x, x0, rtol=0.0, atol=1e-8)
    if stalled:
        res2 = minimize(loss_function, np.asarray(x0, dtype=float), method='Nelder-Mead',
                        options={'maxiter': 4000, 'xatol': 1e-9, 'fatol': 1e-12})
        if np.all(np.isfinite(res2.x)) and np.isfinite(res2.fun) and res2.fun <= res.fun:
            res = res2
    return res


def mde_jsu(fcq: list[float], tau_levels: list[float] = [0.05, 0.25, 0.50, 0.75, 0.95], lit_vol: float = 2.0) -> np.array:
    """
    Minimum Distance CDF fitting to a set of forecasted quantiles.

    Parameters:
    -----------
    fcq : list[float] or np.array
        The forecasted quantiles from the quantile regression.
    tau_levels : list[float]
        The probability levels corresponding to the forecasted quantiles.
    lit_vol : float
        The theoretical daily standard deviation of Brent returns from literature 
        (e.g., 2.0 for 2%) to be used as the starting point for the optimizer.
        
    Returns:
    --------
    np.array
        The estimated parameters of the Johnson SU distribution: [a, b, loc, scale]
    """
    
    if len(fcq) != len(tau_levels):
        raise ValueError("The number of forecasted quantiles must match the number of tau levels.")

    emp_quantiles = np.array(fcq)
    taus = np.array(tau_levels)

    def loss_function(params):
        a, b, loc, scale = params
        
        # Penalti estricto si el optimizador prueba volatilidades o curtosis negativas/cero
        if scale <= 0 or b <= 0:
            return np.inf 
        
        theo_quantiles = johnsonsu.ppf(taus, a, b, loc=loc, scale=scale)
        sse = np.sum((emp_quantiles - theo_quantiles)**2)
        return sse

    # ---------------------------------------------------------
    # MODIFICACIÓN: Inicialización Manual Teórica
    # a=0, b=1 (Forma normal estándar)
    # loc=0.0 (Rendimiento medio esperado)
    # scale=lit_vol (Volatilidad de la literatura)
    # ---------------------------------------------------------
    # Data-driven start instead of the fixed [0,1,0,lit_vol]; the old fixed start
    # left a large share of real OOS days stuck at the initial scale (L-BFGS-B
    # stalling). lit_vol is kept only for backward-compatible signature.
    initial_guess = _mde_jsu_init(fcq, taus)

    bounds = [(None, None), (1e-6, None), (None, None), (1e-6, None)]

    result = _mde_jsu_solve(loss_function, initial_guess, bounds)

    if not result.success and not np.all(np.isfinite(result.x)):
        print(f"Warning: Optimization failed. Message: {result.message}")

    return result.x



def mde_jsu_weighted(fcq: list[float], tau_levels: list[float], initial_params=None, custom_weights=None):
    """
    Fits the JSU distribution to forecasted quantiles using Minimum Distance Estimation.

    By default the fit is UNWEIGHTED (uniform weights) — the plain Adrian et al.
    convention of minimising the unweighted SSE between empirical and theoretical
    quantiles. Pass `custom_weights` to override (e.g. a U-shaped 1/(tau(1-tau))
    tail penalty) if a weighted fit is ever wanted. The function name is kept for
    backwards compatibility with existing call sites.
    """
    emp_quantiles = np.array(fcq)
    taus = np.array(tau_levels)

    # 1. Weighting Mechanism (default: unweighted / uniform)
    if custom_weights is not None:
        weights = np.array(custom_weights)
        if len(weights) != len(taus):
            raise ValueError(f"Length of custom_weights ({len(weights)}) must match tau_levels ({len(taus)}).")
    else:
        # Unweighted MDE: every quantile contributes equally to the SSE.
        weights = np.ones_like(taus)

    def loss_function(params):
        a, b, loc, scale = params
        
        # Strict parameter boundaries
        if scale <= 0 or b <= 0: 
            return np.inf 
            
        theo_quantiles = johnsonsu.ppf(taus, a, b, loc=loc, scale=scale)
        
        # Multiply the squared errors by the dynamic weight vector
        weighted_sse = np.sum(weights * (emp_quantiles - theo_quantiles)**2)
        return weighted_sse

    bounds = [(None, None), (1e-6, None), (None, None), (1e-6, None)]

    if initial_params is None:
        initial_params = _mde_jsu_init(fcq, taus)

    result = _mde_jsu_solve(loss_function, initial_params, bounds)

    if not result.success and not np.all(np.isfinite(result.x)):
        print(f"Warning: Weighted MDE Optimizer failed. {result.message}")

    return result.x

def plot_mde_jsu_fit(returns, mde_params, title="Fitted Johnson SU (MDE)"):
    """
    Visualiza los datos empíricos contra una distribución Johnson SU ajustada
    mediante MDE (Minimum Distance Estimation).
    
    Parameters:
    -----------
    returns : array-like
        Tus datos empíricos (ej. los rendimientos reales proyectados a h días).
    mde_params : np.array o list
        Los parámetros [a, b, loc, scale] devueltos por mde_distfit().
    title : str
        El título principal del gráfico.
    """
    # 1. Limpiar y ordenar los datos empíricos
    returns = np.sort(np.asarray(returns, dtype=float))
    returns = returns[~np.isnan(returns)] # Filtrar NaNs por seguridad
    n = len(returns)
    edf = np.arange(1, n + 1) / n # Distribución empírica acumulada (ECDF)
    
    # 2. Desempaquetar los parámetros del ajuste MDE
    a, b, loc, scale = mde_params

    # 3. Crear el eje X dinámico (basado en los datos y las colas teóricas)
    x_min = min(returns.min(), loc - 4*scale)
    x_max = max(returns.max(), loc + 4*scale)
    x_grid = np.linspace(x_min, x_max, 500)

    # 4. Configurar el lienzo (1 fila, 2 columnas)
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle(title, fontsize=14, fontweight="bold")

    # ─── GRÁFICO IZQUIERDO: PDF (Densidad) ──────────────────────────────────
    ax1 = axes[0]
    
    # Histograma empírico
    ax1.hist(returns, bins=50, density=True, alpha=0.4, color="steelblue", 
             label="Empirical Returns")

    ax1.plot(x_grid, johnsonsu.pdf(x_grid, a, b, loc=loc, scale=scale),
             color="crimson", linewidth=2.5, label="Fitted PDF (JSU)")

    ax1.set_title("Probability Density Function (PDF)")
    ax1.set_xlabel("Returns")
    ax1.set_ylabel("Density")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # ─── GRÁFICO DERECHO: Inverse CDF / Quantile Function ───────────────────
    ax2 = axes[1]

    # Empirical quantile function: probability on x, return value on y
    ax2.step(edf, returns, color="steelblue", alpha=0.7, linewidth=2,
             label="Empirical Quantile", where="post")

    p_grid = np.linspace(0.001, 0.999, 500)
    q_grid = johnsonsu.ppf(p_grid, a, b, loc=loc, scale=scale)
    ax2.plot(p_grid, q_grid, color="crimson", linewidth=2.5,
             label="Quantile Function (JSU)")

    ax2.set_title("Quantile Function / Inverse CDF")
    ax2.set_xlabel("Cumulative Probability")
    ax2.set_ylabel("Returns")
    ax2.set_xlim(0, 1)
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()

def compare_distributions_jsu(returns, hist_mean, hist_std, cond_params, date_str="Eve of the Shock", realized_return=None):
    """
    Visualizes the Oil-at-Risk Early Warning framework.
    Compares the Conditional Forecasted JSU (fitted via MDE on conditional quantiles) 
    against the Historical Baseline Normal distribution.
    
    Parameters:
    -----------
    returns : array-like
        The raw historical returns up to the eve of the forecast.
    hist_mean : float
        Historical mean for the Normal baseline.
    hist_std : float
        Historical standard deviation for the Normal baseline.
    cond_params : tuple or list
        The parameters (gamma, delta, loc, scale) fitted via MDE on the forecasted conditional quantiles.
    date_str : str
        Label for the plot title.
    realized_return : float, optional
        The actual return that occurred during the shock (t+h) to prove the EWS captured it.
    """
    returns = np.sort(np.asarray(returns, dtype=float))
    returns = returns[~np.isnan(returns)]
    n = len(returns)
    edf = np.arange(1, n + 1) / n
    
    # Unpack parameters (a, b, loc, scale for scipy's johnsonsu)
    a_c, b_c, l_c, s_c = cond_params

    # Calculate exactly where the 5% (Downside) and 95% (Upside) risk boundaries lie
    var5_u = norm.ppf(0.05, loc=hist_mean, scale=hist_std)
    var95_u = norm.ppf(0.95, loc=hist_mean, scale=hist_std)
    
    var5_c = johnsonsu.ppf(0.05, a_c, b_c, loc=l_c, scale=s_c)
    var95_c = johnsonsu.ppf(0.95, a_c, b_c, loc=l_c, scale=s_c)

    # Dynamic X-axis to ensure we capture the fat tails and the realized shock
    x_min = min(returns.min(), var5_c * 1.5, realized_return if realized_return else 0)
    x_max = max(returns.max(), var95_c * 1.5, realized_return if realized_return else 0)
    x_grid = np.linspace(x_min, x_max, 1000)
    p_grid = np.linspace(0.001, 0.999, 1000)

    # Calculate PDFs
    pdf_u = norm.pdf(x_grid, loc=hist_mean, scale=hist_std)
    pdf_c = johnsonsu.pdf(x_grid, a_c, b_c, loc=l_c, scale=s_c)

    fig, axes = plt.subplots(1, 2, figsize=(15, 6))
    fig.suptitle(f"Oil-at-Risk Early Warning System: {date_str}", fontsize=16, fontweight="bold")

    # ─── LEFT PLOT: Probability Density Functions (PDF) ────────────────────
    ax1 = axes[0]
    
    # 1. Historical Data (The raw truth)
    ax1.hist(returns, bins=50, density=True, alpha=0.25, color="gray", label="Historical Returns")
    
    # 2. True Historical Baseline (MLE)
    ax1.plot(x_grid, pdf_u, color="black", linestyle="--", linewidth=2.5, 
             label=f"Historical MLE Baseline (VaR 5%: {var5_u:.2f}%)")
    
    # 3. Conditional Forecast (MDE)
    ax1.plot(x_grid, pdf_c, color="crimson", linewidth=2.5, 
             label=f"GaR Conditional Forecast (VaR 5%: {var5_c:.2f}%)")
    
    # 4. SHADING THE TAILS (Visualizing the EWS Alert)
    ax1.fill_between(x_grid, 0, pdf_c, where=(x_grid <= var5_c), color='darkred', alpha=0.4, label="Alert: Forecasted Downside (5%)")
    ax1.fill_between(x_grid, 0, pdf_c, where=(x_grid >= var95_c), color='darkgreen', alpha=0.4, label="Alert: Forecasted Upside (95%)")

    # 5. The Realized Shock (Validating the EWS)
    if realized_return is not None:
        ax1.axvline(realized_return, color='purple', linestyle='-', linewidth=2.5, 
                    label=f"Actual Shock at t+h ({realized_return:.2f}%)")
        
        ax1.annotate('Realized Shock', xy=(realized_return, 0.02), xytext=(realized_return - (x_max-x_min)*0.2, 0.05),
                     arrowprops=dict(facecolor='purple', shrink=0.05), fontsize=10, fontweight='bold', color='purple')

    ax1.set_title("Density Shift: Anticipating the Shock", fontsize=13)
    ax1.set_xlabel("Brent Returns (%)")
    ax1.set_ylabel("Density")
    ax1.legend(loc="upper left", fontsize=9)
    ax1.grid(True, linestyle='--', alpha=0.4)

    # ─── RIGHT PLOT: Quantile Functions (Inverse CDF) ──────────────────────
    ax2 = axes[1]

    # Empirical historical quantiles
    ax2.step(edf, returns, color="gray", alpha=0.5, linewidth=1.5, label="Empirical History", where="post")

    # Unconditional Normal & Conditional JSU Inverse CDFs
    q_uncond = norm.ppf(p_grid, loc=hist_mean, scale=hist_std)
    ax2.plot(p_grid, q_uncond, color="black", linestyle="--", linewidth=2.5, label="Historical Normal Quantiles")

    q_cond = johnsonsu.ppf(p_grid, a_c, b_c, loc=l_c, scale=s_c)
    ax2.plot(p_grid, q_cond, color="crimson", linewidth=2.5, label="Conditional MDE Quantiles")

    # The Realized Shock (mapped to probability space)
    if realized_return is not None:
        realized_prob_c = johnsonsu.cdf(realized_return, a_c, b_c, loc=l_c, scale=s_c)
        ax2.scatter(realized_prob_c, realized_return, color='purple', s=80, zorder=6, label=f"Realized Shock (p={realized_prob_c:.3f})")
        ax2.axhline(realized_return, color='purple', linestyle=':', alpha=0.5)

    # Focus lines on the 5% Tail Risk Shift
    ax2.axvline(0.05, color='gray', linestyle=':', alpha=0.7)
    ax2.scatter(0.05, var5_u, color='black', zorder=5)
    ax2.scatter(0.05, var5_c, color='crimson', s=60, zorder=5)
    
    # Text annotation for the gap
    ax2.annotate(f"VaR Shift: {abs(var5_c - var5_u):.2f}%", 
                 xy=(0.05, (var5_u + var5_c)/2), 
                 xytext=(0.1, (var5_u + var5_c)/2),
                 arrowprops=dict(arrowstyle="->", color='crimson'),
                 color='crimson', fontweight='bold')

    ax2.set_title("Quantile Function: The Downside Risk Gap", fontsize=13)
    ax2.set_xlabel("Cumulative Probability ($\tau$)")
    ax2.set_ylabel("Brent Returns (%)")
    ax2.set_xlim(0, 1)
    ax2.legend(loc="lower right")
    ax2.grid(True, linestyle='--', alpha=0.4)

    plt.tight_layout()
    plt.show()

def generate_oos_parameters(df: pd.DataFrame,
                            x: str,
                            y: str,
                            controls: list[str],
                            quantiles: list[float],
                            h: int,
                            train_end_date: str):
    """
    Executes an Out-of-Sample Expanding Window backtest.
    Avoids look-ahead bias by dynamically adjusting the training window.

    Returns:
    - realized_oos: 1D array with the actual realized returns.
    - params_oos: 2D array with daily [a, b, loc, scale] JSU parameters.
    """

    if controls is None: controls = []
        
    df_work = df.copy()
    if not isinstance(df_work.index, pd.DatetimeIndex):
        df_work.index = pd.to_datetime(df_work.index)
        
    # 1. Prepare variables and shifted target
    cols_to_keep = [y, x] + controls
    df_work = df_work[cols_to_keep]
    target_col = f"{y}_target_h{h}"
    df_work[target_col] = df_work[y].shift(-h)
    
    # 2. Define the Out-of-Sample testing dates
    # Drop ultimate NaNs (the future that hasn't happened yet)
    df_eval = df_work.dropna(subset=[target_col]).copy()
    
    # Test period starts AFTER the train_end_date
    test_dates = df_eval.loc[df_eval.index > train_end_date].index
    
    if len(test_dates) == 0:
        raise ValueError("The train_end_date leaves no valid Out-of-Sample dates to evaluate.")
        
    params_list = []
    realized_list = []
    
    # 3. Expanding Window Loop
    for current_date in tqdm(test_dates, desc=f"OOS Backtesting (h={h})"):
        
        # --- LOOK-AHEAD BIAS PREVENTION ---
        # At 'current_date', we are trying to predict Y_{t+h}.
        # The latest fully realized historical pair we can use for training 
        # is the one from 'h' periods ago. 
        train_cutoff_idx = df_work.index.get_loc(current_date) - h
        if train_cutoff_idx < 0:
            continue # Not enough history to train
            
        cutoff_date = df_work.index[train_cutoff_idx]
        df_train = df_eval.loc[:cutoff_date].dropna().copy()
        
        # Features available TODAY and the future REALIZED target
        features_t = df_work.loc[[current_date]]
        realized_val = features_t[target_col].values[0]
        
        # --- QUANTILE FORECASTING ---
        forecast_q = []
        for q in quantiles:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                try:
                    reg = q_reg(df=df_train, x=x, y=target_col, tau=q, controls=controls, vcov="robust", max_iter=1000)
                except ValueError:
                    reg = q_reg(df=df_train, x=x, y=target_col, tau=q, controls=controls, vcov="iid", max_iter=1000)
                    
                pred = reg.predict(exog=features_t).values[0]
                forecast_q.append(pred)
                
        # --- PARAMETRIC DISTRIBUTION FITTING (MDE) ---
        try:
            params = mde_jsu(fcq=forecast_q, tau_levels=quantiles)
        except Exception:
            # Fallback to NaNs if optimization fails for a specific stressful day
            params = [np.nan, np.nan, np.nan, np.nan]
            
        params_list.append(params)
        realized_list.append(realized_val)
        
    realized_arr = np.array(realized_list)
    params_arr   = np.array(params_list)
    return realized_arr, params_arr


# ###########################################################################
# PART 2 — AZZALINI & CAPITANIO (2003) SKEWED-T DISTRIBUTION
# ###########################################################################


def skewt_pdf(x, df, a, loc, scale):
    """Probability Density Function of the Skewed-t distribution."""
    return scipy_skewt.pdf(x, df, a, loc=loc, scale=scale)

def skewt_cdf(x, df, a, loc, scale):
    """Cumulative Distribution Function of the Skewed-t distribution."""
    return scipy_skewt.cdf(x, df, a, loc=loc, scale=scale)

def skewt_sample(df, a, loc, scale, size):
    """
    Draw i.i.d. samples from a Skewed-t distribution using Inverse Transform Sampling.
    Bypasses the broken .rvs() method in statsmodels.
    """
    # 1. Generate uniform random numbers
    u = np.random.uniform(0, 1, size)
    # 2. Pass through the Inverse CDF
    samples = scipy_skewt.ppf(u, df, a, loc=loc, scale=scale)
    return np.sort(samples)

# ──────────────────────────────────────────────
# 2. HISTORICAL FITTING (MLE) & DIAGNOSTICS
# ──────────────────────────────────────────────

def fit_skewt(data):
    """
    Fits the Skewed-t distribution via Maximum Likelihood Estimation.
    Utilizes the generic continuous MLE fitter.
    """
    data = np.asarray(data, dtype=float)
    data = data[~np.isnan(data)]
    
    if len(data) < 2:
        raise ValueError("fit_skewt requires at least 2 historical observations.")

    # Returns: df, a, loc, scale
    # We provide starting guesses to help the optimizer converge and avoid warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        df_hat, a_hat, loc_hat, scale_hat = scipy_skewt.fit(
            data, 
            10.0, 0.0, # Initial guesses for df and alpha
            loc=np.mean(data), 
            scale=np.std(data)
        )
    return df_hat, a_hat, loc_hat, scale_hat

def skewt_summary(df, a, loc, scale):
    """Prints a formatted summary of the fitted Skewed-t parameters."""
    print("=" * 50)
    print("SKEWED-T (AZZALINI 2003) — FITTED PARAMETERS")
    print("=" * 50)
    print(f"  df     (Tails)         : {df:.6f}")
    print(f"  a      (Skewness)      : {a:+.6f}")
    print(f"  loc    (Location)      : {loc:+.6f}")
    print(f"  scale  (Scale)         : {scale:.6f}")
    print("-" * 50)
    
    skew_dir = "right (positive)" if a > 0 else "left (negative)"
    tail_risk = "extreme" if df < 4 else "moderate"
    print(f"  Skew direction         : {skew_dir}")
    print(f"  Tail thickness         : {tail_risk} (df={df:.2f})")
    
    if df <= 2:
        print("  WARNING: df <= 2. Theoretical variance is infinite.")
    print("=" * 50)

# ──────────────────────────────────────────────
# 3. GROWTH-AT-RISK PIPELINE (MDE & OUT-OF-SAMPLE)
# ──────────────────────────────────────────────

def mde_distfit_skewt(fcq: list[float], tau_levels: list[float] = [0.05, 0.25, 0.50, 0.75, 0.95], lit_vol: float = 2.0) -> np.array:
    """
    Minimum Distance Estimation (MDE) specifically designed for the Skewed-t distribution.
    Fits the continuous Azzalini probability density to the discrete forecasted quantiles.
    """
    emp_quantiles, taus = np.array(fcq), np.array(tau_levels)

    def loss_function(params):
        df, a, loc, scale = params
        # Strict penalty: Degrees of freedom must be > 2 to ensure finite variance in macro models
        # Scale must be strictly positive.
        if scale <= 0 or df <= 2.0: 
            return np.inf 
            
        theo_quantiles = scipy_skewt.ppf(taus, df, a, loc=loc, scale=scale)
        return np.sum((emp_quantiles - theo_quantiles)**2)

    # Initial guess: 
    # df=10.0 (Standard starting point for financial returns)
    # a=0.0 (Normal symmetry starting point)
    initial_guess = [10.0, 0.0, 0.0, lit_vol]
    
    # Bounds: df > 2.01, 'a' and 'loc' unbounded, scale > 1e-6
    bounds = [(2.01, 200.0), (None, None), (None, None), (1e-6, None)]

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        result = minimize(loss_function, initial_guess, method='L-BFGS-B', bounds=bounds)
    
    if not result.success:
        print(f"Warning: Skewed-t MDE Optimization failed. {result.message}")

    return result.x

def plot_mde_skewt_fit(returns, mde_params, title="MDE Skewed-t Fit vs Empirical Data"):
    """
    Plots the MDE-fitted Skewed-t density against the empirical return histogram.
    """
    returns = np.asarray(returns, dtype=float)
    returns = returns[~np.isnan(returns)]
    df_hat, a_hat, loc_hat, scale_hat = mde_params

    x_grid = np.linspace(returns.min(), returns.max(), 500)

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(returns, bins=50, density=True, alpha=0.4, color="steelblue",
            edgecolor="white", label="Empirical Returns")
    ax.plot(x_grid, scipy_skewt.pdf(x_grid, df_hat, a_hat, loc=loc_hat, scale=scale_hat),
            color="darkorange", lw=2.5, label="Skewed-t MDE")
    ax.set_title(title, fontsize=12)
    ax.set_xlabel("Return")
    ax.set_ylabel("Density")
    ax.legend()
    plt.tight_layout()
    plt.show()


def compare_distributions_skewt(returns, uncond_params, cond_params, date_str="", realized_return=None):
    """
    Overlays the unconditional (MLE) and conditional (MDE) Skewed-t densities.
    Optionally marks a realized return on the plot.
    """
    returns = np.asarray(returns, dtype=float)
    x_grid = np.linspace(np.nanpercentile(returns, 0.5), np.nanpercentile(returns, 99.5), 600)

    df_u, a_u, loc_u, scale_u = uncond_params
    df_c, a_c, loc_c, scale_c = cond_params

    pdf_uncond = scipy_skewt.pdf(x_grid, df_u, a_u, loc=loc_u, scale=scale_u)
    pdf_cond   = scipy_skewt.pdf(x_grid, df_c, a_c, loc=loc_c, scale=scale_c)

    fig, ax = plt.subplots(figsize=(11, 5))
    ax.plot(x_grid, pdf_uncond, color="steelblue",   lw=2, linestyle="--", label="Unconditional (MLE)")
    ax.plot(x_grid, pdf_cond,   color="darkorange",  lw=2, label="Conditional (MDE)")

    if realized_return is not None:
        ax.axvline(realized_return, color="crimson", linestyle=":", lw=2,
                   label=f"Realized Return: {realized_return:.2f}%")

    title = "Skewed-t: Conditional vs Unconditional Distribution"
    if date_str:
        title += f"\n{date_str}"
    ax.set_title(title, fontsize=12)
    ax.set_xlabel("Return (%)")
    ax.set_ylabel("Density")
    ax.legend()
    plt.tight_layout()
    plt.show()

    # Print tail probabilities
    q05_c = scipy_skewt.ppf(0.05, df_c, a_c, loc=loc_c, scale=scale_c)
    q05_u = scipy_skewt.ppf(0.05, df_u, a_u, loc=loc_u, scale=scale_u)
    print(f"  5th pct — Conditional: {q05_c:.3f}%  |  Unconditional: {q05_u:.3f}%")
    if realized_return is not None:
        p_c = scipy_skewt.cdf(realized_return, df_c, a_c, loc=loc_c, scale=scale_c)
        p_u = scipy_skewt.cdf(realized_return, df_u, a_u, loc=loc_u, scale=scale_u)
        print(f"  P(R ≤ realized) — Conditional: {p_c:.4f}  |  Unconditional: {p_u:.4f}")


def generate_oos_parameters_skewt(df, x, y, controls, quantiles, h, train_end_date,
                                   lit_vol=2.0):
    """
    Rolling out-of-sample loop: for each OOS date, trains a quantile regression
    on data up to that date, forecasts the h-step-ahead quantiles, then fits a
    Skewed-t via MDE to those forecasted quantiles.

    Look-ahead handling
    -------------------
    Mirrors the Johnson-SU twin ``generate_oos_parameters`` exactly. For each
    out-of-sample date the training set is truncated at ``current_date - h`` so
    that every (x_t, y_{t+h}) pair used for fitting has a target that was already
    realised on or before ``current_date`` — no future leakage. The whole
    post-``train_end_date`` window is evaluated (not just the first h days).

    Returns
    -------
    realized_oos   : list of float  – realized returns in the OOS window
    parameters_oos : list of tuple  – (df, a, loc, scale) for each OOS step
    """
    if controls is None:
        controls = []

    df_work = df.copy()
    if not isinstance(df_work.index, pd.DatetimeIndex):
        df_work.index = pd.to_datetime(df_work.index)
    df_work = df_work.sort_index()

    cols_to_keep = [y, x] + controls
    df_work = df_work[cols_to_keep]
    target_col = f"{y}_target_h{h}"
    df_work[target_col] = df_work[y].shift(-h)

    # OOS dates: every date after train_end_date whose target y_{t+h} is realised.
    df_eval = df_work.dropna(subset=[target_col]).copy()
    test_dates = df_eval.loc[df_eval.index > train_end_date].index
    if len(test_dates) == 0:
        raise ValueError("The train_end_date leaves no valid Out-of-Sample dates to evaluate.")

    realized_oos   = []
    parameters_oos = []

    for current_date in tqdm(test_dates, desc=f"OOS Skewed-t MDE (h={h})"):
        # --- LOOK-AHEAD PREVENTION: train only on pairs realised by current_date ---
        train_cutoff_idx = df_work.index.get_loc(current_date) - h
        if train_cutoff_idx < 0:
            continue
        cutoff_date = df_work.index[train_cutoff_idx]
        df_train = df_eval.loc[:cutoff_date].dropna().copy()

        features_t = df_work.loc[[current_date]]
        real_y = features_t[target_col].values[0]

        try:
            forecast_q = []
            for q in quantiles:
                with warnings.catch_warnings():
                    warnings.simplefilter("ignore")
                    try:
                        reg = q_reg(df=df_train, x=x, y=target_col, tau=q, controls=controls, vcov="robust", max_iter=2000)
                    except ValueError:
                        reg = q_reg(df=df_train, x=x, y=target_col, tau=q, controls=controls, vcov="iid", max_iter=2000)
                forecast_q.append(reg.predict(exog=features_t).values[0])

            params = mde_distfit_skewt(fcq=forecast_q, tau_levels=quantiles, lit_vol=lit_vol)
            realized_oos.append(real_y)
            parameters_oos.append(tuple(params))
        except Exception as e:
            print(f"  Skipped {current_date}: {e}")

    return realized_oos, parameters_oos


